# -*- coding: utf-8 -*-
"""
/***************************************************************************
 save_position
                                 A QGIS plugin
 this plugin is for collecting cordinates and all information of each position
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-12-10
        copyright            : (C) 2021 by issam
        email                : issamalgoubbahi@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load save_position class from file save_position.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .save_position import save_position
    return save_position(iface)
