# -*- coding: utf-8 -*-
"""
/***************************************************************************
 save_position
                                 A QGIS plugin
 this plugin is for collecting cordinates and all information of each position
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-12-10
        git sha              : $Format:%H$
        copyright            : (C) 2021 by issam
        email                : issamalgoubbahi@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction ,QFileDialog

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .save_position_dialog import save_positionDialog
import os.path
from qgis.core import QgsProject , Qgis
import requests  
import json

class save_position:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'save_position_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&save_position')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('save_position', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/save_position/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'save_position'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&save_position'),
                action)
            self.iface.removeToolBarIcon(action)



    def fetchData(self):
        layers = QgsProject.instance().layerTreeRoot().children()
        selectedLayerIndex = self.dlg.comboBox.currentIndex()
        selectedLayer = layers[selectedLayerIndex].layer()

        
        selectedField = self.dlg.comboBox_2.currentText()
        #print(selectedField)
        fieldIndex = self.dlg.comboBox_2.currentIndex()
        #print(fieldIndex)
        selectedLayer.startEditing()
        for f in selectedLayer.getFeatures():
            geom = f.geometry()
            longs = str(geom.asPoint().x())
            lats = str(geom.asPoint().y())
            response = requests.get("https://maps.googleapis.com/maps/api/geocode/json?latlng="+lats+","+longs+"&key=AIzaSyA-oaFfPvGLxrVMay87DG7NVxeMIavePV4")
            #response = requests.get("https://maps.googleapis.com/maps/api/place/textsearch/json?location="+lats+"%2C"+longs+"&key=AIzaSyA-oaFfPvGLxrVMay87DG7NVxeMIavePV4")
            data = response.json()
            print(data)
            json_object = json.dumps(data)
            loaded_r = json.loads(json_object)
            try:
                if selectedField=="Adress" :
                    adress = loaded_r["results"][0]["formatted_address"]
                    selectedLayer.changeAttributeValue(f.id(),fieldIndex , adress)
                if selectedField=="Label" :
                    Label = loaded_r["results"][0]["address_components"][1]["long_name"]
                    print(Label)
                    selectedLayer.changeAttributeValue(f.id(),fieldIndex , Label)
                if selectedField=="Descrption" :
                    descrp = loaded_r["results"][0]["address_components"][1]["types"]
                    str1 = ''.join(e for e in descrp)
                    print(str1)
                    selectedLayer.changeAttributeValue(f.id(),fieldIndex , str1)
                if selectedField=="Lat" :
                    Lat = loaded_r["results"][0]["geometry"]["location"]["lat"]
                    print(Lat)
                    selectedLayer.changeAttributeValue(f.id(),fieldIndex , Lat)
                if selectedField=="Long" :
                    Long = loaded_r["results"][0]["geometry"]["location"]["lng"]
                    print(Long)
                    selectedLayer.changeAttributeValue(f.id(),fieldIndex , Long)
            #print(adress)
            #print("Hello")
            #selectedLayer.changeAttributeValue(f.id(),fieldIndex , adress)
            except:
                print("Adress not found ...")
        selectedLayer.commitChanges()


    def select_output_file(self):
        filename, _filter = QFileDialog.getSaveFileName(self.dlg, "Select   output file ","", '*.csv')
        self.dlg.lineEdit.setText(filename)            

        
    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = save_positionDialog()
            self.dlg.pushButton_3.clicked.connect(self.fetchData)
            self.dlg.pushButton.clicked.connect(self.select_output_file)
        # Fetch the currently loaded layers
        layers = QgsProject.instance().layerTreeRoot().children()
        selectedLayerIndex = self.dlg.comboBox.currentIndex()
        selectedLayer = layers[selectedLayerIndex].layer()
        fieldnames = [field.name() for field in selectedLayer.fields()]
        # Clear the contents of the comboBox from previous runs
        self.dlg.comboBox.clear()
        self.dlg.comboBox_2.clear()
        self.dlg.comboBox_3.clear()
        #self.dlg.lineEdit.clear()
        # Populate the comboBox with names of all the loaded layers
        self.dlg.comboBox.addItems([layer.name() for layer in layers])
        self.dlg.comboBox_3.addItems([layer.name() for layer in layers])

        self.dlg.comboBox_2.addItems(fieldnames)
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            filename = self.dlg.lineEdit.text()
            with open(filename, 'w') as output_file:
                selectedLayerIndex = self.dlg.comboBox.currentIndex()
                selectedLayer = layers[selectedLayerIndex].layer()
                fieldnames = [field.name() for field in selectedLayer.fields()]
                # write header
                line = ','.join(name for name in fieldnames) + '\n'
                output_file.write(line)
                # wirte feature attributes
                for f in selectedLayer.getFeatures():
                    line = ','.join(str(f[name]) for name in fieldnames) + '\n'
                    output_file.write(line)
                    #self.iface.messageBar().pushMessage("Success", "Output file written at " + filename,level=Qgis.Success, duration=3)
                # Do something useful here - delete the line containing pass and
                # substitute with your code.
            pass    
